import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GraphTest } from "../components/graphTest";
import { useEffect, useState } from "react";
import { PropsFrom } from "../lib/TypeHelpers";
import TestComponent from "../components/TestComponent";
import sortingAlgorithms from '../lib/cpp/sortingAlgorithmsMOD'
import countSort from '../lib/cpp/countSortMOD'
import quickSort from '../lib/cpp/quickSortMOD'
import {
  ArrayGenerator,
  JsAndCArray,
} from "../lib/arrayGenerators/ArrayGenerator";
import { QuickSortCPP } from "../lib/sortingAlgorithms/QuickSortCPP";
import { CountSortCPP } from "../lib/sortingAlgorithms/CountSortCPP";
import { PrototypeSortJS } from "../lib/sortingAlgorithms/PrototypeSortJS";
import { QuickSortJS } from "../lib/sortingAlgorithms/QuickSortJS";
import { CountSortJS } from "../lib/sortingAlgorithms/CountSortJS";
import { objectKeys } from "../lib/ObjectKeys";
import SortingDemonstrator from "../components/SortingDemonstration/SortingDemonstrator";
import { SortingAlgorithmName, getInitializedSorters } from "../lib/sortingAlgorithms/All";
import { SortingAlgorithm } from "../lib/sortingAlgorithms/SortingAlgorithm";
import { usePrevious } from "../lib/usePrevious";


//test getting props from other component
type props2 = PropsFrom<typeof TestComponent>;
type props = React.ComponentProps<typeof TestComponent>;

const Home: NextPage = () => {
  const [areClientSide, setAreClientSide] = useState<boolean>(false);
  useEffect(() => {
  
    setAreClientSide(true);
  },[]);
 
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {areClientSide ? 
        
        <SortingDemonstrator 
    
        />
        : <></>}
      </main>
    </div>
  );
};

export default Home;
